version: 2.1
orbs:
    node: circleci/node@5.0.3

jobs:
    build:
        executor:
            name: node/default
            tag: '16.13.2'
        steps:
            - checkout:
                path: ./app
            - node/install-packages:
                app-dir: ./app
                pkg-manager: yarn
            - run: 
                command: yarn add pm2
            - run:
                command: yarn --cwd app build
            - run: ls -la && ls -la ./app
            - run: tar -cvzf build.tgz ./app/node_modules ./app/build ./app/dist
            - run: ls -la
            - persist_to_workspace:
                root: .
                paths:
                - build.tgz
                - ./app/scripts
    deploy-zip-to-server:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: .
        - add_ssh_keys:
            fingerprints:
                - "01:fe:9f:ed:05:ea:d1:07:95:cf:56:e9:61:61:d4:9e"
        - run:
            name: Deploy zip
            command: |
                ls -la
                ssh -o ConnectTimeout=10 $SSH_USER@$SSH_HOST "rm -rf ~/apps/payload-cms/app"
                scp -r build.tgz $SSH_USER@$SSH_HOST:~/apps/payload-cms
                ssh -o ConnectTimeout=10 $SSH_USER@$SSH_HOST "tar -xvf ~/apps/payload-cms/build.tgz -C ~/apps/payload-cms && echo "DONE" && rm -rf ~/apps/payload-cms/build.tgz"
                ssh -o ConnectTimeout=10 $SSH_USER@$SSH_HOST "~/apps/payload-cms/app/node_modules/.bin/pm2"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy-zip-to-server:
                requires:
                - build
                filters:
                    branches:
                        only: main