version: 2
orbs:
  node: circleci/node@16.13.2

jobs:
    build:
        docker:
            - image: cimg/base:stable
        steps:
        - checkout
        - node/install:
            install-yarn: true
        - run: node --version
    deploy:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: /app
        - run:
            name: Deploy Over SSH
            command: |
                ls -la


workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                - build # only deploy once build job has completed
                filters:
                    branches:
                        only: main # only deploy on the main branch