version: 2

jobs:
    build:
        machine:
            image: ubuntu-2004:202010-01
        steps:
        - checkout
        - run:
            name: Deploy Over SSH
            command: |
                ls -la
                node -v
                npm run build
        persist_to_workspace:
            paths: 
                - app
    deploy:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: /app
        - run:
            name: Deploy Over SSH
            command: |
                ls -la


workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                - build # only deploy once build job has completed
                filters:
                    branches:
                        only: main # only deploy on the main branch