version: 2.1
orbs:
    node: circleci/node@5.0.3

jobs:
    build:
        executor:
            name: node/default
            tag: '16.13.2'
        steps:
            - checkout:
                path: ./app
            - node/install-packages:
                app-dir: ./app
                pkg-manager: yarn
            - run:
                command: yarn --cwd app install
            - run: tar -cvzf build.tgz ./app
            - run: ls -la
            - persist_to_workspace:
                root: .
                paths:
                - build.tgz
                - ./app/scripts
    deploy-zip-to-server:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: .
        - add_ssh_keys:
            fingerprints:
                - "01:fe:9f:ed:05:ea:d1:07:95:cf:56:e9:61:61:d4:9e"
        - run:
            name: Deploy zip
            command: |
                scp -r build.tgz $SSH_USER@$SSH_HOST:~/apps/payload-cms
                scp -r scripts $SSH_USER@$SSH_HOST:~/apps/payload-cms/scripts
    deploy:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: .
        - run: 
            command: ls -la
        - run:
            name: Deploy zip
            command: |
                ssh $SSH_USER@$SSH_HOST "ls -la && bash ~/apps/payload-cms/app/scripts/deploy.sh"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy-zip-to-server:
                requires:
                - build
                filters:
                    branches:
                        only: main
            - deploy:
                requires:
                - deploy-zip-to-server
                filters:
                    branches:
                        only: main