version: 2.0
orbs:
    node: circleci/node@5.0.3

jobs:
    build:
        docker:
            - image: cimg/base:stable
        steps:
        - checkout
        - node/run:
            npm-run: build
        - persist_to_workspace:
            root: .
            paths:
                - .
    deploy:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: .
        - run:
            name: Deploy Over SSH
            command: |
                ls -la

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                - build # only deploy once build job has completed
                filters:
                    branches:
                        only: main # only deploy on the main branch