version: 2.1
orbs:
    node: circleci/node@5.0.3

jobs:
    build:
        executor:
            name: node/default
            tag: '16.13.2'
        steps:
            - checkout
            - run: ls -la
            - node/install-packages:
                pkg-manager: yarn
            - run:
                command: yarn run build
            - run: tar -czf build.tgz build dist
            - run: ls -la
            - persist_to_workspace:
                root: .
                paths:
                - build.tgz
    deploy:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: .
        - add_ssh_keys:
            fingerprints:
                - "01:fe:9f:ed:05:ea:d1:07:95:cf:56:e9:61:61:d4:9e"
        - run:
            name: Deploy zip
            command: |
                scp -r build.tgz $SSH_USER@$SSH_HOST:~/apps/payload-cms
        - run:
            name: Deploy zip
            command: |
                ssh $SSH_USER@$SSH_HOST "cd ~/apps/payload-cms && tar -xzf build.tgz && rm build.tgz"


workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                - build # only deploy once build job has completed
                filters:
                    branches:
                        only: main # only deploy on the main branch