version: 2.1
orbs:
    node: circleci/node@5.0.3

jobs:
    build:
        executor:
            name: node/default
            tag: '16.13.2'
        steps:
            - checkout
            - run: ls -la
            - node/install-packages:
                pkg-manager: yarn
            - run:
                command: yarn run build
            - persist_to_workspace:
                root: .
                paths:
                - dist
                - build
    deploy:
        machine:
             image: ubuntu-2004:202010-01
        steps:
        - attach_workspace:
            at: .
        - run:
            name: Deploy Over SSH
            command: |
                ssh -i $SSH_KEY $SSH_USER@$SSH_HOST "ls -la"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                - build # only deploy once build job has completed
                filters:
                    branches:
                        only: main # only deploy on the main branch